version: "3.8"

services:
  llm-chat:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./models:/app/models  # Ensure models persist
    env_file:
      - .env